### ISSUE TITLE
Telekom schafft Spotify-Angebot ab

### ISSUE THREAD

**Issue by maweki** [LinkeEntwicklerInnenLeipzig/webpage#3]
Quelle:
- http://www.focus.de/digital/videos/zu-beliebt-telekom-schafft-spotify-angebot-ab_id_5775775.html

Das Angebot wird zu sehr genutzt, darum schafft man es ab. Nutzung wächst. In den Netzausbau/Infrastruktur investiert niemand.

**Comment by IamNaota** [comment]
Done
